# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Cranky Blog
tagline:          ''
description:      'Tales of a time-crunched club cyclist from Scotland'
url:              http://www.jimmycranky.co.uk
baseurl:          /

author:
  name:           'Jimmy "Cranky" Brough'
  url:            https://twitter.com/mcjimbob

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mcjimbob/mcjimbob.github.io

redcarpet:
  extensions: [tables, autolink]
