# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Cranky's Cycling Blog
tagline:          'I like cycles and code'
description:      ''
url:              http://www.jimmycranky.co.uk
baseurl:          /

author:
  name:           'Jimmy Brough'
  url:            https://twitter.com/mcjimbob

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
