# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Cranky Blog
tagline:          ''
description:      'Just a grumpy, mediocre Scottish club cyclist who sometimes blogs about his hobby'
url:              http://www.jimmycranky.co.uk
baseurl:          /

author:
  name:           'Jimmy "Cranky" Brough'
  url:            https://twitter.com/mcjimbob

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mcjimbob/mcjimbob.github.io
